apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: prediction
  name: prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      service: prediction
  template:
    metadata:
      labels:
        service: prediction
        api: external
    spec:
      containers:
        - image: martinezi/ml-microservice
          name: ml-microservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      volumes:
        - name: docker-secret
          secret:
            secretName: regcred
      restartPolicy: Always
