apiVersion: v1
kind: Service
metadata:
  labels:
    service: prediction
  name: prediction
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    service: prediction
